### ISSUE TITLE
Firmware 04.08.02 not supported?

### ISSUE THREAD

**Issue by pswid** [bosch-thermostat/home-assistant-bosch-custom-component#133]
Hi,

I want to use this integration with Buderus WSW196iT heat pump. It has integrated KM200 interface. After proper configuration, integration starts but shows one device with no entities at all.

![no-entities](https://user-images.githubusercontent.com/78219494/151794828-6f216c5b-92c5-4c7b-bf74-dd5eb50bb668.jpg)

Debug show info that firmware **might** be not supported. Can I do anything to make it working?
[debug.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7970683/debug.txt)

attached bosch_scan.json
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7970690/bosch_scan.zip)

**Comment by Rakon23** [comment]
No entity after update
![Screenshot_20220131-182259_Chrome](https://user-images.githubusercontent.com/93140315/151843568-918c26dd-a851-46bc-a480-b9ea173b1613.jpg)

**Comment by ampstudio666** [comment]
> Hi,
> 
> I want to use this integration with Buderus WSW196iT heat pump. It has integrated KM200 interface. After proper configuration, integration starts but shows one device with no entities at all.
> 
> ![no-entities](https://user-images.githubusercontent.com/78219494/151794828-6f216c5b-92c5-4c7b-bf74-dd5eb50bb668.jpg)
> 
> Debug show info that firmware **might** be not supported. Can I do anything to make it working? [debug.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7970683/debug.txt)
> 
> attached bosch_scan.json [bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/7970690/bosch_scan.zip)

I think Buderus sent updates to the km200 gateways.  My configuration stopped working today with a incompatibility message in home assistant

**Comment by pszafer** [comment]
I released pre release 0.17.2. Can you check it out?

**Comment by pswid** [comment]
Unfortunately update didn't help. Deleting and adding integration again doesn't help either. Debug still shows the same error:

_2022-01-31 20:31:20 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.17.2.
2022-01-31 20:31:20 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2022-01-31 20:31:20 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 192.168.3.223.
2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/uuid
2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/bus
2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/versionFirmware
2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/brand
2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/info
2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/systemType
2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/DateTime
2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt] Found supported device {'value': 'iCom_Low_NSC_v1', 'name': 'Enviline/Compress 6000/7000', 'type': 'NSC_ICOM_GATEWAY'} with id 172
2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt] Found supported device {'value': 'RC300', 'name': 'RC300/RC310/Nefit Moduline 3000', 'type': 'RC300_RC200'} with id 158
2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt] Using model iCom_Low_NSC_v1 as database schema
2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.base] Found device {"value": "iCom_Low_NSC_v1", "name": "Enviline/Compress 6000/7000", "type": "NSC_ICOM_GATEWAY"}
2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.db] Attempt to load database from file /usr/local/lib/python3.9/site-packages/bosch_thermostat_client/db/nsc_icom_gateway/040802.json
2022-01-31 20:31:21 ERROR (MainThread) [custom_components.bosch] You might have unsuporrted firmware version 04.08.02
2022-01-31 20:31:21 DEBUG (MainThread) [custom_components.bosch] Bosch BUS detected: EMS
2022-01-31 20:31:21 INFO (MainThread) [custom_components.bosch] Bosch initialized.
2022-01-31 20:31:21 DEBUG (MainThread) [custom_components.bosch] Registering services.
2022-01-31 20:31:21 DEBUG (MainThread) [custom_components.bosch] Bosch component registered with platforms []._

**Comment by pswid** [comment]
> Unfortunately update didn't help. Deleting and adding integration again doesn't help either. Debug still shows the same error:
> 
> _2022-01-31 20:31:20 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.17.2. 2022-01-31 20:31:20 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration. 2022-01-31 20:31:20 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 192.168.3.223. 2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/uuid 2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/bus 2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/versionFirmware 2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/brand 2022-01-31 20:31:20 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/info 2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /system/systemType 2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.connectors.http] Sending GET request to /gateway/DateTime 2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt] Found supported device {'value': 'iCom_Low_NSC_v1', 'name': 'Enviline/Compress 6000/7000', 'type': 'NSC_ICOM_GATEWAY'} with id 172 2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt] Found supported device {'value': 'RC300', 'name': 'RC300/RC310/Nefit Moduline 3000', 'type': 'RC300_RC200'} with id 158 2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.ivt] Using model iCom_Low_NSC_v1 as database schema 2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.gateway.base] Found device {"value": "iCom_Low_NSC_v1", "name": "Enviline/Compress 6000/7000", "type": "NSC_ICOM_GATEWAY"} 2022-01-31 20:31:21 DEBUG (MainThread) [bosch_thermostat_client.db] Attempt to load database from file /usr/local/lib/python3.9/site-packages/bosch_thermostat_client/db/nsc_icom_gateway/040802.json 2022-01-31 20:31:21 ERROR (MainThread) [custom_components.bosch] You might have unsuporrted firmware version 04.08.02 2022-01-31 20:31:21 DEBUG (MainThread) [custom_components.bosch] Bosch BUS detected: EMS 2022-01-31 20:31:21 INFO (MainThread) [custom_components.bosch] Bosch initialized. 2022-01-31 20:31:21 DEBUG (MainThread) [custom_components.bosch] Registering services. 2022-01-31 20:31:21 DEBUG (MainThread) [custom_components.bosch] Bosch component registered with platforms []._

It's not fixed probably because 040802.json has to be added to .../bosch_thermostat_client/db/**nsc_icom_gateway**/ directory not .../bosch_thermostat_client/db/rc300_rc200/

**Comment by pszafer** [comment]
I know, I think they unified firmware version for both heat pump and RC300.

**Comment by Nakle** [comment]
iCom_Low_NSC_v1
Firmware: **04.07.07** works great.
Finally got 'Return Temperature' back

**Comment by pszafer** [comment]
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.17.3

**Comment by vdg1** [comment]
@pszafer thank you, v0.17.3 works with firmware 04.08.02 on IVT Geo 500.
