### ISSUE TITLE
CT200: Integration stopped working after HA update 2024.9 or after update to firmware 05.00.01

### ISSUE THREAD

**Issue by CheeseEye** [bosch-thermostat/home-assistant-bosch-custom-component#403]
This error originated from a custom integration.

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:302
integration: Bosch thermostat (documentation, issues)
First occurred: 5:17:16 PM (1 occurrences)
Last logged: 5:17:16 PM

You might have unsupported firmware version 05.00.01
![Bosch](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/142225110/aa0b0067-e9f7-4424-b910-350d194bca31)

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:188
First occurred: 5:17:16 PM (2 occurrences)
Last logged: 5:17:17 PM

Detected that custom integration 'bosch' accesses hass.components.persistent_notification. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from persistent_notification directly at custom_components/bosch/__init__.py, line 183: hass.components.persistent_notification.async_create(, please create a bug report at https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by Nunak** [comment]
I have same issue. What I see in the logs very often:
`ERROR (MainThread) [bosch_thermostat_client.connectors.xmpp] Can't connect to XMPP server!. Check your network connection or credentials!`
I didn't change password or something like that.

**Comment by cream68** [comment]
Same issue here!

**Comment by gfre** [comment]
Same here. However Readme says the integration only supports up to 2024.1. So the question is, when  is support for current versions expected?

**Comment by zandhaas** [comment]
Can you please check you installed HA version because version 2024.9 is a not exiting version current latest HA version is 2024.4.4

If you upgrade to CT200 integration version 0.25.1 all should be working again.
This version supports both HA versions > 2024.1 and Easycontrol version 05.00.01

**Comment by gfre** [comment]
Does v0.25.1 support RC300 integration for HA versions > 2024.1? 
For me the IVT RC300  integration still not working with latest versions.
![Screenshot_2024-04-24-11-14-02-015_io homeassistant companion android](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/24912555/2e8c48fd-0d28-492e-a641-c234585e1e50)

**Comment by cream68** [comment]
![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/29704325/a4f11dd7-7727-41ce-87bd-a24ed2928f45)


![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/29704325/15df9411-6fa8-40cb-9407-5841aee2abb8)

**Comment by CheeseEye** [comment]
> Can you please check your installed HA version because version 2024.9 is a not exiting version. Current latest HA version is 2024.4.4
> 
> If you upgrade to CT200 integration version 0.25.1 all should be working again. This version supports both HA versions > 2024.1 and Easycontrol version 05.00.01

Perfect, thanks for you help

**Comment by cream68** [comment]
any updates?

**Comment by zandhaas** [comment]
I have an easycontrol device and that working fine. 
I do not have a RC300. So do not know anything about it.

**Comment by CR6-SE** [comment]
For me the Integration works but I can Change the Presets of the circuit Units. Eveything else ist working fine for me.

**Comment by pszafer** [comment]
Let's close it.
If integration is not working for somebody, provide some logs. for most people it's working.

**Comment by CR6-SE** [comment]
Here are the log, when I try to change a programm. 

2024-04-30 04:35:02.651 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /programs/list
2024-04-30 04:35:02.651 WARNING (MainThread) [custom_components.bosch] Bosch object of entity Esszimmer is no longer available. Error requesting data from /programs/list
2024-04-30 04:35:07.966 DEBUG (MainThread) [zigpy.application] Feeding watchdog
2024-04-30 04:35:11.459 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x9666](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
2024-04-30 04:35:11.459 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x9666](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:12.002 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x47D5](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
2024-04-30 04:35:12.002 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x47D5](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:12.654 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /zones/zn2/clockProgram
2024-04-30 04:35:12.865 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x024B](lumi.motion.ac02): Device seen - marking the device available and resetting counter
2024-04-30 04:35:12.865 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x024B](lumi.motion.ac02): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:14.565 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0180](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
2024-04-30 04:35:14.565 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x0180](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:17.995 DEBUG (MainThread) [zigpy.application] Feeding watchdog
2024-04-30 04:35:18.657 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /programs/list
2024-04-30 04:35:18.657 WARNING (MainThread) [custom_components.bosch] Bosch object of entity Wohnzimmer is no longer available. Error requesting data from /programs/list
2024-04-30 04:35:19.435 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xEDCE](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
2024-04-30 04:35:19.435 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xEDCE](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:24.660 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /zones/zn2/clockProgram
2024-04-30 04:35:27.644 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x9C75](Plug 01): Device seen - marking the device available and resetting counter
2024-04-30 04:35:27.644 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x9C75](Plug 01): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:28.023 DEBUG (MainThread) [zigpy.application] Feeding watchdog
2024-04-30 04:35:30.662 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /programs/list
2024-04-30 04:35:30.662 WARNING (MainThread) [custom_components.bosch] Bosch object of entity Badezimmer is no longer available. Error requesting data from /programs/list
2024-04-30 04:35:31.999 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x4586](Plug 01): Device seen - marking the device available and resetting counter
2024-04-30 04:35:31.999 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x4586](Plug 01): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:34.301 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x5031](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
2024-04-30 04:35:34.301 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x5031](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:36.664 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /programs/list
2024-04-30 04:35:36.664 WARNING (MainThread) [custom_components.bosch] Bosch object of entity Flur is no longer available. Error requesting data from /programs/list
2024-04-30 04:35:38.053 DEBUG (MainThread) [zigpy.application] Feeding watchdog
2024-04-30 04:35:40.190 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x6F8E](lumi.sensor_magnet.aq2): Device seen - marking the device available and resetting counter
2024-04-30 04:35:40.190 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x6F8E](lumi.sensor_magnet.aq2): Update device availability -  device available: True - new availability: True - changed: False
2024-04-30 04:35:42.667 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /programs/list
2024-04-30 04:35:42.667 WARNING (MainThread) [custom_components.bosch] Bosch object of entity Küche is no longer available. Error requesting data from /programs/list

**Comment by pszafer** [comment]
@CR6-SE please open your own issue with Bosch scan attached and all the logs
