### ISSUE TITLE
Contact between thermostat and home assistant seems to get lost

### ISSUE THREAD

**Issue by krisgeusens** [bosch-thermostat/home-assistant-bosch-custom-component#454]
**Describe the bug**
The connection/reporting between the thermostat and home assistant seenms to break.

**To Reproduce**
It happens daily, not on the same time. Restarting the integration solves the problem until next day.
The entities don't show unavailable, but no new values come in and no settings can be changed.

**Expected behavior**
that it keeps working withour restart.

**Screenshots**

**Version**
  - HA version?
  Core
2024.11.1
Supervisor
2024.11.2
Operating System
13.2
Frontend
20241106.2
  - HA Bosch component version?
  0.26.3
  - Python Bosch HTTP client version?
 no idea where to get that

** Debug SCAN **
** IMPORTANT **
Go to Developer tools in Home Assistant, choose Service tab and choose `bosch.debug_scan`
Download file to your computer and upload it somewhere eg. https://jsonblob.com/
There is not such tab in my home assistant/developer tools

**Additional context**

**Comment by JBakers** [comment]
Same here.
Today my sensors stopped updating at 11, no logs arround that time, but an hour later this showed in my log:

`Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/bosch/__init__.py:360
integratie: Bosch thermostat (documentatie, problemen)
Eerst voorgekomen: 12:06:22 (1 gebeurtenissen)
Laatst gelogd: 12:06:22

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/sensors/energy.py", line 158, in update
    result = await self._connector.get(self.build_uri(page_number=i))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 131, in get
    raise DeviceException(f"Error requesting data from {path}")
bosch_thermostat_client.exceptions.DeviceException: Error requesting data from /energy/history?entry=779

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 360, in recording_sensors_update
    await entity.bosch_object.update(time=now)
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/sensors/energy.py", line 162, in update
    f"Can't update data for {self.name}. Trying uri: {self._data[URI]}. Error message: {err}"
                                                      ~~~~~~~~~~^^^^^
KeyError: 'uri'`

**Comment by mmakaay** [comment]
Same here. Yesterday, I also noticed that the EasyControl app on my iPhone was very sluggish, and I found some references by Bosch about server maintenance.

One thing I wondered about, is if the issue could have something to do with recovering from a connection loss / timeout while talking to the Bosch systems. What strengthens this idea, is that restarting Home Assistant of the integration brings back the functionality right away.

I just started writing an automation for handling an integration reload, but @JBakers beat me to it.
Thanks for the example! 👍

**Comment by JackPoint** [comment]
There is maintenance since yesterday, it's listed on this (Dutch) website: https://www.nefit-bosch.nl/consument/na-je-aankoop/actuele-meldingen

> 12 november 2024 - In verband met werkzaamheden aan de server is het mogelijk dat de thermostaat tijdelijk geen verbinding maakt met het internet. Gebruikers kunnen hiervan hinder ondervinden bij het bedienen van de thermostaat via de app. Probeer het in dit geval later nog eens. Je kunt de thermostaat uiteraard altijd handmatig bedienen. De verwarming blijft gewoon werken - ook als er tijdelijk geen internetverbinding is. Onze excuses voor het eventuele ongemak.

It's a bit confusing since the app did show a notification about maintenance but that one shows the maintenance is on 15 november

**Comment by mmakaay** [comment]
Yes, the information is a bit scattered. For those not too well-versed in Dutch, the Bosch site tells us:

> November 12th - due to server maintenance, it is possible that the thermostat temporarily cannot connect to the internet. Users can experience issues when controlling the thermostat using the app. In such case, try again later. Of course, it is always possible to control the thermostat manually. The heating will remain operational - also while the internet connection fails. Our apologies for the inconvenience.

**Comment by gawsneakerz** [comment]
> There is maintenance since yesterday, it's listed on this (Dutch) website: https://www.nefit-bosch.nl/consument/na-je-aankoop/actuele-meldingen
> 
> > 12 november 2024 - In verband met werkzaamheden aan de server is het mogelijk dat de thermostaat tijdelijk geen verbinding maakt met het internet. Gebruikers kunnen hiervan hinder ondervinden bij het bedienen van de thermostaat via de app. Probeer het in dit geval later nog eens. Je kunt de thermostaat uiteraard altijd handmatig bedienen. De verwarming blijft gewoon werken - ook als er tijdelijk geen internetverbinding is. Onze excuses voor het eventuele ongemak.
> 
> It's a bit confusing since the app did show a notification about maintenance but that one shows the maintenance is on 15 november

Thanks, makes sense now, integration was working fine for the last month. Since this week having issues...

**Comment by Petkay2059** [comment]
Here same problem.
Bosch thermostat sensors are totally lost in HA since this afternoon. Hope someone finds a fix for this problem.
Thermostat was pused a firmware update 05.02.00 after Bosch server maintenance.

**Comment by Petkay2059** [comment]
Ok, definate workaround would be installing EMS bus Gateway device to the Bosch Nefit boiler. It sends all the data directy to HA using MQTT. No need of the server of Bosch.

**Comment by mkruseonline** [comment]
Seems to work again after  a restart of KMS and reload Integration

**Comment by Petkay2059** [comment]
Restart KMS?
You have to help me here, i'm a newbee.
I've restarted HA and reloaded the integration, no luck for me.

**Comment by mkruseonline** [comment]
Wrong naming, km200 - the Internet gateway in the heater (I have a Buderus)

**Comment by mqatgit** [comment]
> Wrong naming, km200 - the Internet gateway in the heater (I have a Buderus)

How do we do that - restart the gateway thingy? Mine is a MX300 Connect-Key, and it seems to have similar troubles. But the Bosch app sees it fine, locally. No cloud connecting involved, I believe.

**Comment by mkruseonline** [comment]
At Buderus Heater I can simply plug out the Bus connection cable. The the Gateway has no power and restarts

**Comment by krisgeusens** [comment]
my Buderus app now says 'maintenance on 17th. I will wait until that is over before taking any other action.

**Comment by mqatgit** [comment]
> At Buderus Heater I can simply plug out the Bus connection cable. The the Gateway has no power and restarts

Okay, thanks. Different device, it seems, but I'll try something similar...

**Comment by mqatgit** [comment]
Didn't work...

**Comment by BlizzardTheWolf** [comment]
I seem to have the same problem too. Bosch CT200 and HA on latest version. Randomly gets lost and a HA reboot fixes it.

**Comment by krisgeusens** [comment]
There is no more maintenance message on my app, hopefully it's solved now

**Comment by neworld** [comment]
> Randomly gets lost and a HA reboot fixes it.

It would be great if integration could restore the connection like other integrations. No cloud-based service provider guarantee stable API,.

**Comment by warior456** [comment]
still getting this error, has been happening after having to reload because entities stopped updating
(i'm not sure where the detailed log is)

This error originated from a custom integration.

Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:309
integration: Bosch thermostat (documentation, issues)
First occurred: November 17, 2024 at 20:38:19 (29 occurrences)
Last logged: 22:40:47

You might need to check your password.

**Comment by Petkay2059** [comment]
This device will do the trick.
No more need of the cloud service of Bosch.
https://bbqkees-electronics.nl/product/gateway-e32-v2-ethernet-wifi-edition-v2/

**Comment by warior456** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:
    b'\x16\x03\x01\x02'
      ^
2024-11-18 22:41:58.794 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2024-11-18 22:41:58.794 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2024-11-18 22:41:58.794 ERROR (MainThread) [custom_components.bosch] You might need to check your password.
2024-11-18 22:42:04.455 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:Invalid method encountered:
    b'\x16\x03\x01\x02'
      ^
2024-11-18 22:42:09.006 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:
    b'\x16\x03\x01\x02'
      ^
2024-11-18 22:42:43.943 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:43.944 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:43.944 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:43.944 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:43.949 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:43.950 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:43.950 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:43.950 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-11-18 22:42:55.928 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:
    b'\x16\x03\x01\x02'
      ^
2024-11-18 22:43:19.155 INFO (MainThread) [custom_components.bosch] Setting up Bosch component version 0.26.2.
2024-11-18 22:43:19.155 DEBUG (MainThread) [custom_components.bosch] Initializing Bosch integration.
2024-11-18 22:43:19.172 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway as 101085142.
2024-11-18 22:43:35.242 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:
    b'\x16\x03\x01\x02'
      ^
2024-11-18 22:43:49.643 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2024-11-18 22:43:49.643 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2024-11-18 22:43:49.643 ERROR (MainThread) [custom_components.bosch] You might need to check your password.
```

**Comment by krisgeusens** [comment]
mmh, no more maintenance messages in the app but today I faced this issue again.

**Comment by hardysim** [comment]
I have this problem as well I guess.

I have a Buderus heater with a RC310 and a MB LANi which used to work just fine for the last year but the connection started to become broken some days ago. I cannot get a connection via Home Assistant or any of the bosch / buderus apps.

Removing the jack plug of the MB LANi to do a power cycle seems to help but only a few minutes (around 2 to 30) after which the connection is broken again. Resetting the MB LANi via the reset-password setting on the RC310 did "help" but just like power cycling it (it stops working after a few minutes).

**Comment by krisgeusens** [comment]
> mmh, no more maintenance messages in the app but today I faced this issue again. Edit: yesterday evening I have rebooted my thermostat, let's hope it's ok now

it looks like it's sorted for me.

**Comment by msd252** [comment]
I am still having the same issue. The connection between HA and Bosch just drops out and no values are changeable or updatable. A restart of HA fixes the issue. Does anyone have any insight on what is causing this?

**Comment by msd252** [comment]
> This device will do the trick. No more need of the cloud service of Bosch. https://bbqkees-electronics.nl/product/gateway-e32-v2-ethernet-wifi-edition-v2/

Sadly this does not support smart TRVs so cannot be a complete replacement of the Bosch EasyControl in my case.

**Comment by msd252** [comment]
Just as an update - I restarted everything (thermostat, HA, Boiler) and I have not experienced a drop out in over a week. I think it is now working and problem closed for me at least!

**Comment by krisgeusens** [comment]
I was thinking the same but last night it happened again. restarting teh integration sorts it out.

**Comment by warior456** [comment]
it's been more stable recently

**Comment by jansenfd** [comment]
Regularly stops working, restarting integration fixes this issue. Very annoying during winter season... Is this actively being investigated at this moment?

**Comment by krisgeusens** [comment]
it looks like it happened again yesterday evening, but I'm not sure as I was thinkering with it at that time.

But it's much more stable now as it was before.

**Comment by phryx4711** [comment]
Hi,
I made a workaround by Setting up an Automation in HA, that reloads the Integration if the indoor temp value hasn‘t changed for an hour.
This is of course no fix for the problem, but helps nontheless

**Comment by JBakers** [comment]
Still happening...
I made the automation above to have a temporary fix.

**Comment by jansenfd** [comment]
Since recently complete integration stopped working. It appears also that the developer for this integration is looking for another developer to take over this integration. 

Too bad was using this integration alot.

**Comment by mmakaay** [comment]
> another developer to take over this integration

That's not completely true. There is a request for a second developer to ease the burden of maintenance, unless I missed some update on this. As a single maintainer, load and pressure can become quite high (talking out of experience here), and being able to share that burden is a great good in open source projects.

**Comment by ArnoutVos** [comment]
With my ISP (NL: KPN FttH) having issues last week (large number of PPPoE disconnects) this problem pops up every day after maintenance at ISP level or at Bosch API cloud level. Workaround for me is to reload the integration. It's the connection between this integration and Bosch API cloud which gets terminated and the integration not reconnecting.
I'm running latest version of HA, HACS and this integration. I'm using OPNsense 25.1 as Firewall, in 'conservative' mode which means that the firewall is not terminating connections that fast (maybe that's a precondition for this problem?).
I'm eager to help fix this problem, I can reproduce it and do some additional logging as well. What steps should I take to help you? @mmakaay

**Comment by mmakaay** [comment]
While I appreciate that enormously, I am not the maintainer of the component. 
That would be Pawel (@pszafer).

**Comment by ArnoutVos** [comment]
Ok, lets reproduce it. I turned on debug logging for the integration.
First, the current (OK) state before reproducing. Two 'flows' active at firewall level (ntopng):
![Image](https://github.com/user-attachments/assets/cef348de-3ce9-4c87-84bd-56e74a611f2d)

Firewall sessions. Notice the amount of sessions 'established' and their age. Very old, still active. IP .40 is homeassistant, IP .6 is the Bosch EasyControl:
![Image](https://github.com/user-attachments/assets/ad17b755-9fb6-473e-a733-3437549e3399)

Reset the sessions:
![Image](https://github.com/user-attachments/assets/764f36aa-4b39-42cf-98da-7321b12a624d)

Within one minute, warnings start to pop up at the logging:
![Image](https://github.com/user-attachments/assets/7cc81169-c602-4046-ae55-c678605ca9c3)

One minute later, the Miele integration notices the disconnect as well:
![Image](https://github.com/user-attachments/assets/394d9710-70db-436f-b4dc-df6d17de14e1)

6 minutes later, the integration errors:
![Image](https://github.com/user-attachments/assets/a6786802-16b2-4207-b70f-9e4cbf2e7730)

`2025-02-15 12:06:23.211 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/sensors/energy.py", line 158, in update
    result = await self._connector.get(self.build_uri(page_number=i))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 131, in get
    raise DeviceException(f"Error requesting data from {path}")
bosch_thermostat_client.exceptions.DeviceException: Error requesting data from /energy/history?entry=1727
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 360, in recording_sensors_update
    await entity.bosch_object.update(time=now)
  File "/usr/local/lib/python3.13/site-packages/bosch_thermostat_client/sensors/energy.py", line 162, in update
    f"Can't update data for {self.name}. Trying uri: {self._data[URI]}. Error message: {err}"
                                                      ~~~~~~~~~~^^^^^
KeyError: 'uri'`

After this error, the warnings are silent for minutes, but start to appear again.
No new data, graph is staling:
![Image](https://github.com/user-attachments/assets/b9c7a088-ad54-4dd5-bec7-1dc333a319ff)

**Comment by ArnoutVos** [comment]
Today I applied an update to my router software which triggers this problem. But the pattern is different: everytime the router goes down, the Bosch integration stalls (no new data). When I reload the integration, it takes another 5-10 mins to get new data. While this is happening, the following errors are in the log. Again, there is that 'Task' exception again, which is maybe a sign of problems in the error handling as well:

```
2025-02-19 12:25:54.476 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for Notifications. Trying uri: /notifications. Error message: Error requesting data from /notifications
2025-02-19 12:25:55.360 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2025-02-19 12:25:55.361 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2025-02-19 12:25:55.361 ERROR (MainThread) [custom_components.bosch] You might need to check your password.
2025-02-19 12:26:00.477 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for thermalDisinfect lastResult. Trying uri: /dhwCircuits/dhw1/thermalDisinfect/lastResult. Error message: Error requesting data from /dhwCircuits/dhw1/thermalDisinfect/lastResult
2025-02-19 12:26:06.479 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for thermalDisinfect state. Trying uri: /dhwCircuits/dhw1/thermalDisinfect/state. Error message: Error requesting data from /dhwCircuits/dhw1/thermalDisinfect/state
2025-02-19 12:26:12.480 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for thermalDisinfect weekDay. Trying uri: /dhwCircuits/dhw1/thermalDisinfect/weekDay. Error message: Error requesting data from /dhwCircuits/dhw1/thermalDisinfect/weekDay
2025-02-19 12:26:18.482 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for hotWaterSystem. Trying uri: /dhwCircuits/dhw1/hotWaterSystem. Error message: Error requesting data from /dhwCircuits/dhw1/hotWaterSystem
2025-02-19 12:26:24.483 WARNING (MainThread) [bosch_thermostat_client.sensors.sensor] Can't update data for humidity. Trying uri: /zones/zn1/humidity. Error message: Error requesting data from /zones/zn1/humidity
2025-02-19 12:26:24.484 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 437, in thermostat_refresh
    await self.component_update(BINARY_SENSOR, event_time)
  File "/config/custom_components/bosch/__init__.py", line 405, in component_update
    entities = self.hass.data[DOMAIN][self.uuid][component_type]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'binary_sensor'
2025-02-19 12:26:31.077 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2025-02-19 12:26:31.078 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2025-02-19 12:26:31.078 ERROR (MainThread) [custom_components.bosch] You might need to check your password.
2025-02-19 12:27:11.805 ERROR (MainThread) [bosch_thermostat_client.gateway.easycontrol] Couldn't find device model. Got product ID: None
2025-02-19 12:27:11.806 ERROR (MainThread) [custom_components.bosch] Your device is unknown null
2025-02-19 12:27:11.806 ERROR (MainThread) [custom_components.bosch] You might need to check your password.
```

**Comment by JackPoint** [comment]
This is still an issue, see #473 and #404

**Comment by JBakers** [comment]
Yup still happening here also. When WiFi gos down, integration needs te be restarted for it to work again

**Comment by krisgeusens** [comment]
is there any other solution than automation to restart ?

**Comment by JBakers** [comment]
Not completed. Still happening
